# Generated by Django 4.2.4 on 2023-08-15 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_orderitem_order"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="items",
            new_name="products",
        ),
    ]
